name: go-test
on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Run go tests
        run: go test -race -count 1 ./... -timeout=3m
